sudo: false
language: node_js
node_js:
  - 10 # use nodejs v10 LTS
cache: npm
branches:
  only:
    - master # build master branch only
script:
  - mkdir download
  - cd download
  - mkdir re
  - cd re
  - curl -O 'https://dist.torproject.org/torbrowser/9.5.3/torbrowser-install-win64-9.5.3_zh-CN.exe'
  - cd ..
  - tar cjf - re/ |split -b 20m - dl.tar.bz2.
  - echo "copy /b dl.tar.bz2.* dl.tar.bz2" > end.bat
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: master
  local-dir: download
