sudo: false
language: node_js
node_js:
  - 10 # use nodejs v10 LTS
cache: npm
branches:
  only:
    - master # build master branch only
script:
  - mkdir download
  - cd download
  - mkdir re
  - cd re
  - curl -O 'https://net.geo.opera.com/opera/stable/windows?utm_tryagain=yes&utm_source=(direct)_via_opera_com&utm_medium=doc&utm_campaign=(direct)_via_opera_com_https&http_referrer=missing_via_opera_com&utm_site=opera_com'
  - cd ..
  - tar cjf - re/ |split -b 20m - op.tar.bz2.
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: master
  local-dir: download
